# Use netlify to build the site
[build]
  command = "hugo --minify"
  base = "techarge/"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.87"


[[plugins]]
package = "netlify-plugin-chromium"

[[plugins]]
package = "netlify-plugin-lighthouse"

# Requires paid account: https://www.debugbear.com/docs/getting-started-api-cli
#[[plugins]]
#package = "netlify-build-plugin-debugbear"

# Requires paid account: see: https://docs.pagewatch.dev/guide/netlify.html
#[[plugins]]
#package = "netlify-plugin-pagewatch"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html",
  ]

  # Recurse through all the links and asset references on your page, starting
  # at the entrypoints
  recursive = true

  # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
  # by default. Enabling pretty mode makes the output easier on the eyes.
  pretty = true

  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = ["gonts.googleapis.com", "fonts.gstatic.com"]

  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = []

  # Report on all broken links to external pages.
  # Enabling this will make your tests more brittle, since you can't control
  # external pages.
  checkExternal = false

  # Enable to check references to source maps, source map sources etc.
  # Many build tools don't emit working references, so this is disabled by default
  followSourceMaps = false