baseURL = "https://techarge.co.uk/"
languageCode = "en-us"
title = "Techarge Site"
rssLimit = 20
copyright = "2021 Techarge. All rights reserved"

[author]
	name = "Ling Li"
	email = "info@techarge.co.uk"
[module]
	[[module.imports]]
	    disable = false
		ignoreConfig = false
		ignoreImports = false
		path = "github.com/gohugoio/hugo-mod-jslibs/alpinejs"
	[[module.imports]]
	    disable = false
		ignoreConfig = false
		ignoreImports = false
		path = "github.com/gohugoio/hugo-mod-jslibs/turbolinks"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"
	featured_image = "feature_image"
    site_link = "site_link"

[privacy]
  [privacy.disqus]
    disable = false

  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false

  [privacy.instagram]
    disable = false
    simple = false

  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false

  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false

  [privacy.youtube]
    disable = false
    privacyEnhanced = false
