baseURL = "https://techarge.co.uk/"
languageCode = "en-us"
title = "Techarge Site"

[module]
	[[module.imports]]
	    disable = false
		ignoreConfig = false
		ignoreImports = false
		path = "github.com/gohugoio/hugo-mod-jslibs/alpinejs"
	[[module.imports]]
	    disable = false
		ignoreConfig = false
		ignoreImports = false
		path = "github.com/gohugoio/hugo-mod-jslibs/turbolinks"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "My description"
    dateFormat = "Mon, Jan 2, 2006"


[Permalinks]
    post = "/:filename/"

[taxonomies]
	author = "authors"
	tag = "tags"
	category = "categories"
	featured_image = "feature_image"
