module.exports = {
    purge: ['layouts/**/*.html'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        container: {
            center: true,
        },
        screens: {
            'xs': '400px',
            'sm': {'min': '640px'},
            'md': {'min': '768px'},
            'lg': {'min': '1024px'},
            'xl': {'min': '1280px'},
            '2xl': {'min': '1536px'},
        },
        extend: {
            colors: {
                'tc-orange': '#FF8C21',
                'tc-blue': '#36C9C6',
                'tc-yellow': '#F4F1BB',
                'tc-grey': '#E6EBE0',
                'tc-green': '#AEDAD9',
                'tc-dark-green': '#9BC1BC',
                'tc-dark-grey': '#6C6C6C',
                'tc-light-black': '#3A3A3A',
            },
            height: {
                '20px': '20px',
                '26px': '26px',
                '60px': '60px',
                '165px': '165px',
                '194px': '194px',
                'fit-c': 'fit-content'
            },
            width: {
                '32px': '32px',
                '60px': '60px',
                '85px': '85px',
                '98px': '98px',
                '148px': '148px',
                '165px': '165px',
                '180px': '180px',
                '194px': '194px',
                '200px': '200px',
                '210px': '210px',
                'fit-c': 'fit-content'
            },
            padding: {
                '10px': '10px',
                '20px': '20px',
                '25px': '25px',
                '31px': '31px',
                '36px': '36px',
                '35px': '35px',
                '37px': '37px',
                '40px': '40px',
                '44px': '44px',
                '45px': '45px',
                '48px': '48px',
                '50px': '50px',
                '52px': '52px',
                '56px': '56px',
                '58px': '58px',
                '60px': '60px',
                '65px': '65px',
                '70px': '70px',
                '75px': '75px',
                '80px': '80px',
                '90px': '90px',
                '95px': '95px',
                '100px': '100px',
                '110px': '110px',
                '120px': '120px',
                '125px': '125px',
                '155px': '155px',
                '185px': '185px',
                '230px': '230px',
                '310px': '310px',
            },
            margin: {
                '-40px': '-40px',
                '10px': '10px',
                '15px': '15px',
                '13px': '13px',
                '20px': '20px',
                '25px': '25px',
                '27px': '27px',
                '28px': '28px',
                '30px': '30px',
                '40px': '40px',
                '50px': '50px',
                '60px': '60px',
                '70px': '70px',
                '75px': '75px',
                '95px': '95px',
                '115px': '115px',
                '128px': '128px',

            },
            inset: {
                '75px': '75px',
            },
            fontSize: {
                '11px': '11px',
                '18px': '18px',
            },
            gap: {
                '18px': '18px',
                '20px': '20px',
                '21px': '21px',
                '25px': '25px',
                '26px': '26px',
                '33px': '33px',
                '41px': '41px',
                '46px': '46px',
                '75px': '75px',
                '85px': '85px',
            },
            borderRadius: {
                '20px': '20px',
            },
            animation: {
                'slideInFromLeft': 'slideInFromLeft 1s ease-in-out 0s 1',
                'slideInFromRight': 'slideInFromRight 1s ease-in-out 0s 1',
                'fadeInFromBottom': 'fadeInFromBottom 1.5s ease-in 0s 1',
            },
            keyframes: {
                slideInFromLeft: {
                    '0%': {transform: 'translateX(-100%);', opacity: '0.25;'},
                    '50%': {opacity: '0.75;'},
                    '100%': {transform: 'translateX(0);', opacity: '1;'},
                },
                slideInFromRight: {
                    '0%': {transform: 'translateX(100%);', opacity: '0.25;'},
                    '50%': {opacity: '0.75;'},
                    '100%': {transform: 'translateX(0);', opacity: '1;'},
                },
                fadeInFromBottom: {
                    '0%': {transform: 'translateY(80px);', opacity: '0;'},
                    '50%': {opacity: '0.75;'},
                    '100%': {transform: 'translateY(0);', opacity: '1;'},
                },
            },
        },
    },
    variants: {
        extend: {},
    },
    plugins: [],
};
